#!/usr/bin/env lua

json = require "cjson"

printj = function(...) print(json.encode(...)) end

local cmd = "true"

carg = arg[1]
local shift = function()
  table.remove(arg,1)
  carg = arg[1]
end

-- flags
local do_json = false
local do_print = false
local process = function() end
local BEGIN = function() end
local END = function() end

while true do
  if not carg then break end
  if carg == "-j" then
    do_json = true
  elseif carg == "-p" then
    do_print = true
  elseif carg == "-f" then
    shift()
    process, err = loadfile(carg)
    if err then error(err) end
  elseif carg == "-l" then
    shift()
    require(carg)
  elseif carg == "-BEGIN" then
    shift()
    BEGIN, err = loadstring(carg)
    if err then error(err) end
  elseif carg == "-END" then
    shift()
    END, err = loadstring(carg)
    if err then error(err) end
  else
    process, err = loadstring(table.concat(arg, " "))
    if err then error(err) end
    break
  end
  shift()
end

BEGIN()
for l in io.lines() do
  -- _ needs to be in global env, not shadowed by loop variable in this block
  _ = l
  if do_json then _ = json.decode(_) end
  process()
  if do_json  then _ = json.encode(_) end
  if do_print then print(_) end
end
END()
